# Generated by Django 3.0.5 on 2020-04-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APPModel',
            new_name='APPModels',
        ),
    ]
