# Generated by Django 3.0.5 on 2020-04-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0002_auto_20200422_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodels',
            name='Source',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='OutSource',
        ),
    ]
