# Generated by Django 3.0.5 on 2020-04-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0004_remove_appmodels_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('KeyApi', models.CharField(max_length=255)),
                ('Des', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='APPModels',
        ),
    ]
