# Generated by Django 3.0.5 on 2020-04-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0005_auto_20200422_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
